spring.application.name=springbootcaching
server.port=8080

# redis host and port details
spring.data.redis.host=localhost
spring.data.redis.port=6379

# default cache details
spring.cache.redis.time-to-live=600000 #10 minutes to expire
spring.cache.type=redis