spring.application.name=1_basicUserService

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Tells Hibernate to use the H2 database dialect, so it generates SQL compatible with H2.
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enables the H2 web console UI at /h2-console for viewing tables and running SQL queries.
spring.h2.console.enabled=true

# Automatically updates the database schema based on your JPA entities (adds new columns/tables without deleting data).
spring.jpa.hibernate.ddl-auto=update
